### ISSUE TITLE
Class constructor xxxxx cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kpturner** [michaelolof/vuex-class-component#1]
Having become frustrated with `vuex-typescript` I thought I would give your library a whirl because it seems to give me more of what I am looking for.  However, the information in the README is a little lightweight so I am having difficulties implementing a test module to try it out.  

I based my test on the example in the README which immediately gave me a lot of errors and warnings because of my linting rules etc - mainly around the lack of type definitions on method and parameter signatures and the missing `private` and `public` declarations. 

This example finally built OK for me:
```
import { VuexModule, mutation, action, getter, Module } from 'vuex-class-component';

interface Name {
    firstname: string;
    lastname: string;
}

@Module({ namespacedPath: 'ClassTestStore/' })
export class ClassTestStore extends VuexModule {

    private firstname: string = 'Michael';
    private lastname: string = 'Olofinjana';
    @getter public specialty: string = 'JavaScript';
    @getter public occupation: string = 'Developer';

    @mutation
    public changeName({ firstname, lastname }: Name): void {
        this.firstname = firstname;
        this.lastname = lastname;
    }

    @action()
    public async doSomethingAsync(): Promise<void> {
        setTimeout(() => {
            console.log('foo'); // tslint:disable-line
        }, 1000);
    }

    @action()
    public async doAnotherAsyncStuff(payload: any): Promise<void> {
        setTimeout(() => {
            console.log(payload); // tslint:disable-line
        }, 1000);
    }

    public get fullName(): string {
        return this.firstname + ' ' + this.lastname;
    }
}
```
which may or may not follow the pattern you intended.

Next I added the module to vuex as instructed and created a `vxm`:

```
import Vuex from 'vuex';
import { IState } from '../types';
import { ClassTestStore } from './modules/class_module';

export const classTestStore = ClassTestStore.ExtractVuexModule(ClassTestStore );

export const store = new Vuex.Store<IState>({
    modules: {
        classTestStore
    }
});

export const vxm = {
    classTestStore: ClassTestStore.CreateProxy(store, ClassTestStore)
};
```

To test I wanted to try both `vxm` and the module directly in a component.  Your example looks like this:

```
@Component
export class MyComponent extends Vue {
    
    user = UserStore.CreateProxy( this.$store, UserStore );

    mounted() {
      /** Now we can easily call */
      this.user.fullName; /** Michael Olofinjana */
      this.user.occupation; /** Developer */
      this.user.changeName({ firstname:"John", lastname:"Doe" });
    }
  }
```
Question: What is the `@Component` decorator here for?

My component is defined like this:
```
import { vxm } from '../store';
import { ClassTestStore } from '../store/modules/class_module.ts';

export default Vue.extend({
    data() {
        return {
            classTestStore1: vxm.classTestStore,
            classTestStore2: ClassTestStore.CreateProxy( this.$store, ClassTestStore )
        };
    },
    mounted() {
        this.classTestStore1.fullName; /** Michael Olofinjana */
        this.classTestStore1.occupation; /** Developer */
        this.classTestStore1.changeName({ firstname:"John", lastname:"Doe" });

        this.classTestStore2.fullName; /** Michael Olofinjana */
        this.classTestStore2.occupation; /** Developer */
        this.classTestStore2.changeName({ firstname:"John", lastname:"Doe" });
    }
});
```
**Problem 1**
This line will not transpile:
` classTestStore2: ClassTestStore.CreateProxy( this.$store, ClassTestStore )` 
as typescript cannot find `CreateProxy` as a method on `ClassTestStore` even though it works when creating `vxm`.  
Putting that aside (by commenting it out) I then get

**Problem 2**
There is no intellisense on ` this.classTestStore1`.  It does not know about `.fullname` or `.occupation` or `.changeName` - but it does not fail to build either.

**Problem 3**
At runtime I get:
```
 TypeError: Class constructor ClassTestStore cannot be invoked without 'new'
    at getter (/Users/turnerk/Documents/GitHub/private/squareadmin/node_modules/vuex-class-component/dist/getters.js:6:22)
    at module.exports.__decorate (src/app/store/modules/class_module.ts:4:0)
    at Object.module.exports.__webpack_exports__.a (src/app/store/modules/class_module.ts:46:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 695d4698d653203c9bcf:25:0)
    at Object.module.exports.Object.defineProperty.value (src/app/store/index.ts:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 695d4698d653203c9bcf:25:0)
    at webpackContext (server-bundle.js:4466:9)
    at getModule (.nuxt/store.js:57:0)
    at Object.module.exports.map../index.ts (.nuxt/store.js:22:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 695d4698d653203c9bcf:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 695d4698d653203c9bcf:25:0)
    at Object.<anonymous> (.nuxt/server.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 695d4698d653203c9bcf:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10) statusCode: 500, name: 'TypeError' }
```
The last problem is the most fundamental so I need to get that sorted first.

Can you assist with any of this because I really would like to get it working. Obviously I may have made some incorrect assumptions when interpreting the example.

**Comment by michaelolof** [comment]
**About Problem 1**
If I'm judging correctly from the sample you presented up there. You haven't imported ClassTestStore correctly in your Vue component (You imported classTestStore). Hence the error.

**About Problem 2**
This is actually a .vue file issue. For some reason, the typescript engine that comes with Vetur can't infer the types correctly and just assumes it to be type any. So you have to explicitly cast it to ClassTestStore.

**About Problem 3**
I think this is similar to problem 1. You haven't imported the class correctly.

**Also on a side note**, 
Please refer to the readme documentation on how to properly use actions.
Unless you're using a raw action mode (see readme) you shouldn't use the async/await

**Comment by michaelolof** [comment]
Yes the library does rely on es7 decorators so you have to make sure this property **"experimentalDecorators": true,** is set in your tsconfig.json file.

**Comment by kpturner** [comment]
Yes I am already using that particular option otherwise decorators probably would not work at all.  I don't think it can be that.  However, are you saying that `target` should be `es7` rather than `es6`?
What about `lib`?  Currently I have that set as `[ "es2017", "dom" ]`

**Comment by kpturner** [comment]
With regard to your side note about actions.  I need some clarification.  Your example has this:
```
@action() 
  doAnotherAsyncStuff(payload) { ... }
```
but that will not not pass linting rules as it stands.  You get the following errors:
```
      TS2345: Argument of type 'TypedPropertyDescriptor<(payload: any) => void>' is not assignable to parameter of type 'TypedPropertyDescriptor<(payload?: an
y) => Promise<any>>'.
  Type '(payload: any) => void' is not assignable to type '(payload?: any) => Promise<any>'.
    Type 'void' is not assignable to type 'Promise<any>'.
```
It seems to me that you have to define a return type for the function like this:
`public doAnotherAsyncStuff(payload: any): Promise<void> { .... return a Promise ... }`
Do you concur?

**Comment by kpturner** [comment]
Update: These are my options but I still get **Problem 3**
```
"compilerOptions": {
        "module": "commonjs",
        "lib": [ "es2018", "dom" ],
        "target": "es2018",
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "skipLibCheck": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "allowJs": true,
        "mapRoot": "./",
        "rootDir": "./"
    }
```

**Comment by kpturner** [comment]
Maybe you have a small example repo with things working that I can clone and compare?

**Comment by michaelolof** [comment]
Your target only specifies what you'd want your final output to be.

> but that will not not pass linting/TS rules as it stands. You get the following errors:

This was actually intentional. Actions by default return promises. It is a vuex thing not a vuex-class-component thing. Returning any thing other than a promise actually breaks type system since the action proxies are making dispatch calls behind the scenes which always return promises.


> Maybe you have a small example repo with things working that I can clone and compare?

Would probably upload a simple repo addressing that.

**Comment by michaelolof** [comment]
Here is a working repo
https://github.com/michaelolof/vuex-class-component-simple

**Comment by michaelolof** [comment]
Closing this due to no activity
